#!/bin/bash


chosen=$(printf "Power Off\nRestart\nLock" |  dmenu -i -nb "#292c35" -sb "#c179d4" -sf "#292c35" ) 

case "$chosen" in
  "Power Off") poweroff ;;
  "Restart") reboot ;;
  "Lock") slock ;;
  *) exit 1 ;;
esac
